import Blogsidebar from "@/components/BlogsSideBar/Blogsidebar";

export const metadata = {
    title: 'Blogs',
    description: 'Generated by create next app',
  }
  

const UserLayout = ({ children }) => {
	return (
		<div className="lg:flex ">
            <div className="lg:w-[20%] w-[100%]"><Blogsidebar></Blogsidebar></div>
                    <div className="p-10">{children}</div>
		</div>
	);
};

export default UserLayout;